CREATE TABLE tbl_devices (
id int(11) NOT NULL AUTO_INCREMENT,
device_id varchar(12) NOT NULL,
password varchar(20) NOT NULL,
ip varchar(16) NOT NULL,
mask varchar(16) NOT NULL,
macaddress varchar(25) NOT NULL,
supernode1 varchar(25) NOT NULL,
supernode2 varchar(25) NOT NULL,	
domain text NULL,								  
name text NOT NULL,
email varchar(60) NOT NULL,
level tinyint(1) NOT NULL DEFAULT 0,
timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
address text COLLATE utf8_general_ci NULL,
phone varchar(32) COLLATE utf8_general_ci NULL,
notify tinyint(1) NOT NULL DEFAULT 0,
contact text COLLATE utf8_general_ci NULL,
created_by varchar(20) NULL,
active tinyint(1) NOT NULL DEFAULT 1,
account_requested tinyint(1) NOT NULL DEFAULT 0,
account_denied tinyint(1) NOT NULL DEFAULT 0,
max_user_size int(20)  NOT NULL DEFAULT 255,
PRIMARY KEY (id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;